[package]
name = "rustlanges-components-core"
description = "RustLangES internal core components library"
version = { workspace = true }
edition = "2024"
license = "MIT"

[dependencies]
constcat = "0.6.1"
